name: Daily File Upload

on:
  schedule:
    - cron: '0 0 * * *'  # This runs every day at midnight UTC
  workflow_dispatch:  # Allow manual trigger from GitHub UI

jobs:
  daily-file-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download the file from a website
      run: |
        curl -o targets.nested.json https://data.opensanctions.org/datasets/20241115/eu_fsf/targets.nested.json  # Replace with your URL

    - name: Move old files to "old" folder
      run: |
        mkdir -p old  # Create the "old" folder if it doesn't exist
        mv *.txt old/  # Move all txt files to the "old" folder

    - name: Add and commit new file
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add -A
        git commit -m "Add new file and move old files"
        git push origin main  # Change to your default branch if different

    - name: Upload new file
      run: |
        mv targets.nested.json targets.nested.json  # Ensure the new file is added
        git add targets.nested.json
        git commit -m "Upload targets.nested.json"
        git push origin main  # Push the new file to GitHub
