name: Daily File Upload

on:
  schedule:
    - cron: '0 0 * * *'  # This runs every day at midnight UTC
  workflow_dispatch:  # Allow manual trigger from GitHub UI

jobs:
  daily-file-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # Use v4 for the latest updates

    - name: Download the file from a website
      run: |
        curl -o targets.nested.json https://data.opensanctions.org/datasets/20241115/eu_fsf/targets.nested.json

    - name: Move old files to "old" folder
      run: |
        mkdir -p old  # Create the "old" folder if it doesn't exist
        mv *.json old/  # Move all json files to the "old" folder

    - name: Add and commit new file
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add -A
        git commit -m "Add new file and move old files"
        git push origin main  # Change to your default branch if different

    - name: Add and commit new file
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add -A
        git commit -m "Add new file and move old files" || echo "No changes to commit"
        git push origin main  # Ensure the correct branch is specified
